#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ethanslist.android.Resource", IsApplication=true)]

namespace ethanslist.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int cityListViewItem = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int cityPickerListView = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int citySelectedText = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int feedResultsListView = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int maxRentSeekBar = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int maxRentTextView = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int minBathroomPicker = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int minBedroomPicker = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int minRentSeekBar = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int minRentTextView = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int photoImageView = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int postingDetailsText = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int postingImageView = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int postingTitleText = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int searchButton = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int searchTextField = 2131034121;
			
			// aapt resource value: 0x7f050016
			public const int stateListViewItem = 2131034134;
			
			// aapt resource value: 0x7f050005
			public const int statePickerListView = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int strut = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int strut2 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int strut3 = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int strut4 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int strut5 = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CityRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FeedResults = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FeedResultsRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PostingDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Search = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StateRow = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
