#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ethanslist.android.Resource", IsApplication=true)]

namespace ethanslist.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PullToRefresharp.Resource.Attribute.contentViewId = global::ethanslist.android.Resource.Attribute.contentViewId;
			global::PullToRefresharp.Resource.Attribute.fastScrollThumbWidth = global::ethanslist.android.Resource.Attribute.fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Attribute.headerIconDrawable = global::ethanslist.android.Resource.Attribute.headerIconDrawable;
			global::PullToRefresharp.Resource.Attribute.headerId = global::ethanslist.android.Resource.Attribute.headerId;
			global::PullToRefresharp.Resource.Attribute.headerTextColor = global::ethanslist.android.Resource.Attribute.headerTextColor;
			global::PullToRefresharp.Resource.Attribute.ptrHeaderBackground = global::ethanslist.android.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::ethanslist.android.Resource.Attribute.pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Attribute.pullDownTension = global::ethanslist.android.Resource.Attribute.pullDownTension;
			global::PullToRefresharp.Resource.Attribute.pullEnabled = global::ethanslist.android.Resource.Attribute.pullEnabled;
			global::PullToRefresharp.Resource.Attribute.pullToRefreshText = global::ethanslist.android.Resource.Attribute.pullToRefreshText;
			global::PullToRefresharp.Resource.Attribute.refreshingText = global::ethanslist.android.Resource.Attribute.refreshingText;
			global::PullToRefresharp.Resource.Attribute.releaseToRefreshText = global::ethanslist.android.Resource.Attribute.releaseToRefreshText;
			global::PullToRefresharp.Resource.Attribute.snapbackDuration = global::ethanslist.android.Resource.Attribute.snapbackDuration;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::ethanslist.android.Resource.Color.ptrsharp_sb_gradient_end;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::ethanslist.android.Resource.Color.ptrsharp_sb_gradient_start;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = global::ethanslist.android.Resource.Color.ptrsharp_sb_header_text;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::ethanslist.android.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::PullToRefresharp.Resource.Dimension.fastscroll_thumb_width = global::ethanslist.android.Resource.Dimension.fastscroll_thumb_width;
			global::PullToRefresharp.Resource.Drawable.progress_medium_holo = global::ethanslist.android.Resource.Drawable.progress_medium_holo;
			global::PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::ethanslist.android.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow = global::ethanslist.android.Resource.Drawable.serious_business_arrow;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow2 = global::ethanslist.android.Resource.Drawable.serious_business_arrow2;
			global::PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = global::ethanslist.android.Resource.Drawable.spinner_20_inner_holo;
			global::PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = global::ethanslist.android.Resource.Drawable.spinner_20_outer_holo;
			global::PullToRefresharp.Resource.Id.header = global::ethanslist.android.Resource.Id.header;
			global::PullToRefresharp.Resource.Id.header_container = global::ethanslist.android.Resource.Id.header_container;
			global::PullToRefresharp.Resource.Id.icon = global::ethanslist.android.Resource.Id.icon;
			global::PullToRefresharp.Resource.Id.pullDownProgressIndicator = global::ethanslist.android.Resource.Id.pullDownProgressIndicator;
			global::PullToRefresharp.Resource.Id.text = global::ethanslist.android.Resource.Id.text;
			global::PullToRefresharp.Resource.Layout.ptrsharp_header = global::ethanslist.android.Resource.Layout.ptrsharp_header;
			global::PullToRefresharp.Resource.String.library_name = global::ethanslist.android.Resource.String.library_name;
			global::PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::ethanslist.android.Resource.String.ptrsharp_pull_to_refresh;
			global::PullToRefresharp.Resource.String.ptrsharp_refreshing = global::ethanslist.android.Resource.String.ptrsharp_refreshing;
			global::PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = global::ethanslist.android.Resource.String.ptrsharp_release_to_refresh;
			global::PullToRefresharp.Resource.Style.HoloProgressMedium = global::ethanslist.android.Resource.Style.HoloProgressMedium;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_fastScrollThumbWidth;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_headerId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = global::ethanslist.android.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public const int fastScrollThumbWidth = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ptrsharp_sb_header_text_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int theme_devicedefault_background = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int fastscroll_thumb_width = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ethanslist_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int placeholder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int progress_medium_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ptrsharp_serious_business_gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int serious_business_arrow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int serious_business_arrow2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int spinner_20_inner_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int spinner_20_outer_holo = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int cityListViewItem = 2131230720;
			
			// aapt resource value: 0x7f080027
			public const int cityPickerListView = 2131230759;
			
			// aapt resource value: 0x7f080017
			public const int citySelectedText = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int deleteSearchButton = 2131230742;
			
			// aapt resource value: 0x7f080006
			public const int drawerLayout = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int drawerListView = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int feedResultsListView = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int frameLayout = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public const int header = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int header_container = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int icon = 2131230736;
			
			// aapt resource value: 0x7f08000a
			public const int imageGridView = 2131230730;
			
			// aapt resource value: 0x7f08001d
			public const int maxRentSeekBar = 2131230749;
			
			// aapt resource value: 0x7f080020
			public const int maxRentTextView = 2131230752;
			
			// aapt resource value: 0x7f080005
			public const int menuRowTextView = 2131230725;
			
			// aapt resource value: 0x7f080024
			public const int minBathroomPicker = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int minBedroomPicker = 2131230755;
			
			// aapt resource value: 0x7f08001c
			public const int minRentSeekBar = 2131230748;
			
			// aapt resource value: 0x7f08001f
			public const int minRentTextView = 2131230751;
			
			// aapt resource value: 0x7f080002
			public const int photoImageView = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int postingDateText = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int postingDetailsText = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int postingImageView = 2131230729;
			
			// aapt resource value: 0x7f080003
			public const int postingTitleText = 2131230723;
			
			// aapt resource value: 0x7f08000f
			public const int pullDownProgressIndicator = 2131230735;
			
			// aapt resource value: 0x7f080012
			public const int recentCitiesList = 2131230738;
			
			// aapt resource value: 0x7f08000c
			public const int saveListingButton = 2131230732;
			
			// aapt resource value: 0x7f080025
			public const int saveSearchButton = 2131230757;
			
			// aapt resource value: 0x7f080013
			public const int savedSearchListView = 2131230739;
			
			// aapt resource value: 0x7f080019
			public const int searchButton = 2131230745;
			
			// aapt resource value: 0x7f080014
			public const int searchCityText = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int searchInformationText = 2131230741;
			
			// aapt resource value: 0x7f080018
			public const int searchTextField = 2131230744;
			
			// aapt resource value: 0x7f080028
			public const int stateListViewItem = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int statePickerListView = 2131230758;
			
			// aapt resource value: 0x7f08001a
			public const int strut = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int strut2 = 2131230747;
			
			// aapt resource value: 0x7f08001e
			public const int strut3 = 2131230750;
			
			// aapt resource value: 0x7f080021
			public const int strut4 = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int strut5 = 2131230754;
			
			// aapt resource value: 0x7f080011
			public const int text = 2131230737;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CityRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FeedResults = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FeedResultsRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewMenuRow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PostingDetails = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ptrsharp_header = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RecentCities = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SavedSearches = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SavedSearchRow = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Search = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SelectCity = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int StateRow = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060007
			public const int DrawerCloseDescription = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int DrawerOpenDescription = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int app_name = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int hello = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ptrsharp_pull_to_refresh = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ptrsharp_refreshing = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ptrsharp_release_to_refresh = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HoloProgressMedium = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Custom = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresharpWrapper = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 12
			public const int PullToRefresharpWrapper_fastScrollThumbWidth = 12;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
